### ISSUE TITLE
Only a question...

### ISSUE THREAD

**Issue by lucianomlima** [brunolemos/react-native-template-modern#1]
You have declared jest@latest in devDependencies.json, but when I tried your template, the downloaded jest version from template is the same jest version that is downloaded by the react native init in version 0.56.0.

Why did you still keep the jest in devDependencies.json file?

Btw, awesome work!

**Comment by brunolemos** [comment]
Hi! 

@lucianomlima I think this and a couple other dev dependencies can be removed, like babel-core. I was trying to make jest work but I wasn't able to make jest+typescript work with 0.56 yet, were you?

I saw some people saying I may need to use the `resolutions` field of `package.json` to make sure babel 7 is being used to make ts-jest work with 0.56.

**Comment by lucianomlima** [comment]
Yeah, in my test don't work too. But in a project without Typescript is working fine with RN 0.56.0.
Yeah! You can put in your `package.template.json`:

```json
"resolutions": {
  "babel-core": "^7.0.0-bridge.0"
}
```

To force any package that uses babel-core@6.x.x to use version 7 instead.
But I not try here xD
